//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactorTB()
        {
            this.CartTBs = new HashSet<CartTB>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int SCPID { get; set; }
        public Nullable<System.DateTime> DataNow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartTB> CartTBs { get; set; }
        public virtual SCP SCP { get; set; }
    }
}
