//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderListTB
    {
        public int ID { get; set; }
        public int OrderItemID { get; set; }
        public int CustomerID { get; set; }
        public int Code { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual CustomerTB CustomerTB { get; set; }
        public virtual OrderItemTB OrderItemTB { get; set; }
    }
}
