//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItemTB()
        {
            this.OrderListTBs = new HashSet<OrderListTB>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int BuyCount { get; set; }
        public int SellPrice { get; set; }
        public int TotalPrice { get; set; }
        public int Code { get; set; }
    
        public virtual ProductTB ProductTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderListTB> OrderListTBs { get; set; }
    }
}
