//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTB()
        {
            this.OrderItemTBs = new HashSet<OrderItemTB>();
        }
    
        public int ID { get; set; }
        public short Type { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public int Barcode { get; set; }
        public int Price { get; set; }
        public int Mojod { get; set; }
        public Nullable<short> CPU { get; set; }
        public string ScreenSize { get; set; }
        public Nullable<short> Ram { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemTB> OrderItemTBs { get; set; }
    }
}
