//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCP()
        {
            this.FactorTBs = new HashSet<FactorTB>();
        }
    
        public int ID { get; set; }
        public int CartID { get; set; }
        public int ProductID { get; set; }
    
        public virtual CartTB CartTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactorTB> FactorTBs { get; set; }
        public virtual PhoneTB PhoneTB { get; set; }
        public virtual SCP SCP1 { get; set; }
        public virtual SCP SCP2 { get; set; }
        public virtual ToolsTB ToolsTB { get; set; }
    }
}
